2025-05-08 15:04:02,691 - reporting_generator - INFO - [reporting_generator.py:30] - Génération d'un rapport pour le module vuln_scan
2025-05-08 15:04:02,699 - reporting_generator - INFO - [reporting_generator.py:71] - Rapport généré avec succès: generated_reports/report_vuln_scan_20250508_150402.html
2025-05-08 15:11:36,528 - reporting_generator - INFO - [reporting_generator.py:30] - Génération d'un rapport pour le module vuln_scan
2025-05-08 15:11:36,548 - reporting_generator - INFO - [reporting_generator.py:71] - Rapport généré avec succès: generated_reports/report_vuln_scan_20250508_151136.html
2025-05-08 15:12:07,132 - reporting_generator - INFO - [reporting_generator.py:30] - Génération d'un rapport pour le module vuln_scan
2025-05-08 15:12:07,140 - reporting_generator - INFO - [reporting_generator.py:71] - Rapport généré avec succès: generated_reports/report_vuln_scan_20250508_151207.html
2025-05-08 15:15:12,593 - reporting_generator - INFO - [reporting_generator.py:30] - Génération d'un rapport pour le module vuln_scan
2025-05-08 15:15:12,607 - reporting_generator - INFO - [reporting_generator.py:71] - Rapport généré avec succès: generated_reports/report_vuln_scan_20250508_151512.html
2025-05-08 15:21:42,991 - reporting_generator - INFO - [reporting_generator.py:30] - Génération d'un rapport pour le module vuln_scan
2025-05-08 15:21:42,997 - reporting_generator - INFO - [reporting_generator.py:71] - Rapport généré avec succès: generated_reports/report_vuln_scan_20250508_152142.html
2025-05-08 17:07:24,722 - reporting_generator - INFO - [reporting_generator.py:30] - Génération d'un rapport pour le module vuln_scan
2025-05-08 17:07:24,730 - reporting_generator - INFO - [reporting_generator.py:71] - Rapport généré avec succès: generated_reports/report_vuln_scan_20250508_170724.html
2025-05-08 17:38:28,416 - reporting_generator - INFO - [reporting_generator.py:30] - Génération d'un rapport pour le module vuln_scan
2025-05-08 17:38:28,441 - reporting_generator - INFO - [reporting_generator.py:71] - Rapport généré avec succès: generated_reports/report_vuln_scan_20250508_173828.html
2025-05-09 10:38:24,112 - reporting_generator - INFO - [reporting_generator.py:30] - Génération d'un rapport pour le module vuln_scan
2025-05-09 10:38:24,128 - reporting_generator - INFO - [reporting_generator.py:71] - Rapport généré avec succès: generated_reports/report_vuln_scan_20250509_103824.html
2025-05-09 11:23:12,412 - reporting_generator - INFO - [reporting_generator.py:30] - Génération d'un rapport pour le module vuln_scan
2025-05-09 11:23:12,431 - reporting_generator - INFO - [reporting_generator.py:71] - Rapport généré avec succès: generated_reports/report_vuln_scan_20250509_112312.html
2025-05-15 21:23:24,448 - reporting_generator - INFO - [reporting_generator.py:32] - Génération d'un rapport PDF pour le module sniffer
2025-05-15 21:23:24,468 - reporting_generator - ERROR - [reporting_generator.py:86] - Erreur lors de la génération du rapport pdf: 'dict object' has no attribute 'file_size'
Traceback (most recent call last):
  File "/home/oebn/Projet-Scan/services/reporting_generator.py", line 64, in generate_report
    rendered = template.render(**data)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oebn/Projet-Scan/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/oebn/Projet-Scan/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "templates/sniffer_report_template.html", line 42, in top-level template code
    <p><strong>Taille du fichier:</strong> {{ stats.file_size|filesizeformat }}</p>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oebn/Projet-Scan/venv/lib/python3.11/site-packages/jinja2/filters.py", line 710, in do_filesizeformat
    bytes = float(value)
            ^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'file_size'
2025-05-15 21:30:30,382 - reporting_generator - INFO - [reporting_generator.py:32] - Génération d'un rapport HTML pour le module vuln_scan
2025-05-15 21:30:30,390 - reporting_generator - INFO - [reporting_generator.py:81] - Rapport HTML généré avec succès: generated_reports/report_vuln_scan_20250515_213030.html
2025-05-15 21:30:30,391 - reporting_generator - INFO - [reporting_generator.py:32] - Génération d'un rapport PDF pour le module vuln_scan
2025-05-15 21:30:30,947 - reporting_generator - INFO - [reporting_generator.py:74] - Rapport PDF généré avec succès: generated_reports/report_vuln_scan_20250515_213030.pdf
2025-05-15 21:46:35,690 - reporting_generator - INFO - [reporting_generator.py:259] - Génération d'un rapport pdf pour capture réseau avec données préparées
2025-05-15 21:46:35,691 - reporting_generator - INFO - [reporting_generator.py:32] - Génération d'un rapport PDF pour le module sniffer
2025-05-15 21:46:35,714 - reporting_generator - ERROR - [reporting_generator.py:86] - Erreur lors de la génération du rapport pdf: 'list object' has no attribute 'items'
Traceback (most recent call last):
  File "/home/oebn/Projet-Scan/services/reporting_generator.py", line 64, in generate_report
    rendered = template.render(**data)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oebn/Projet-Scan/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/home/oebn/Projet-Scan/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "templates/sniffer_report_template.html", line 97, in top-level template code
    {% for protocol, count in stats.protocols.items() %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oebn/Projet-Scan/venv/lib/python3.11/site-packages/jinja2/utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'list object' has no attribute 'items'
2025-05-15 21:54:11,736 - reporting_generator - INFO - [reporting_generator.py:259] - Génération d'un rapport pdf pour capture réseau avec données préparées
2025-05-15 21:54:11,737 - reporting_generator - INFO - [reporting_generator.py:32] - Génération d'un rapport PDF pour le module sniffer
2025-05-15 21:54:13,801 - reporting_generator - INFO - [reporting_generator.py:74] - Rapport PDF généré avec succès: generated_reports/report_sniffer_20250515_215411.pdf
2025-05-15 21:58:30,632 - reporting_generator - INFO - [reporting_generator.py:259] - Génération d'un rapport pdf pour capture réseau avec données préparées
2025-05-15 21:58:30,635 - reporting_generator - INFO - [reporting_generator.py:32] - Génération d'un rapport PDF pour le module sniffer
2025-05-15 21:58:32,807 - reporting_generator - INFO - [reporting_generator.py:74] - Rapport PDF généré avec succès: generated_reports/report_sniffer_20250515_215830.pdf
2025-05-22 23:52:26,200 - reporting_generator - INFO - [reporting_generator.py:259] - Génération d'un rapport pdf pour capture réseau avec données préparées
2025-05-22 23:52:26,209 - reporting_generator - INFO - [reporting_generator.py:32] - Génération d'un rapport PDF pour le module sniffer
2025-05-22 23:52:28,630 - reporting_generator - INFO - [reporting_generator.py:74] - Rapport PDF généré avec succès: generated_reports/report_sniffer_20250522_235226.pdf
2025-05-23 00:00:20,970 - reporting_generator - INFO - [reporting_generator.py:32] - Génération d'un rapport HTML pour le module vuln_scan
2025-05-23 00:00:20,977 - reporting_generator - INFO - [reporting_generator.py:81] - Rapport HTML généré avec succès: generated_reports/report_vuln_scan_20250523_000020.html
2025-05-23 00:00:20,977 - reporting_generator - INFO - [reporting_generator.py:32] - Génération d'un rapport PDF pour le module vuln_scan
2025-05-23 00:00:21,990 - reporting_generator - INFO - [reporting_generator.py:74] - Rapport PDF généré avec succès: generated_reports/report_vuln_scan_20250523_000020.pdf
